spring:
  application:
    name: crypto
  datasource:
    url: jdbc:h2:mem:crypto
    driver-class-name: org.h2.Driver
    username: username
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2

price-aggregation-url:
  binance: https://api.binance.com/api/v3/ticker/bookTicker
  huobi: https://api.huobi.pro/market/tickers
